### ISSUE TITLE
Address Document Shepherd Comments

### ISSUE THREAD

**Issue by linuxwolf** [linuxwolf/bmeck-ids#1]
- [x] Explicitly note in the obsoleted media types that implementations should use `text/javascript` instead (within "Interoperability Considerations" or "Restrictions on Usage")
- [x] Update section title "Registration" to "IANA Considerations"
- [x] Remove 2119 reference and boilerplate
- [x] Remove authors from "Acknowledgements"

**Comment by mathiasbynens** [comment]
This item:

- [x] Update section title "Registration" to "IANA Considerations"

…has already been completed.
