### ISSUE TITLE
Address feedback from Mary Barnes

### ISSUE THREAD

**Issue by mathiasbynens** [linuxwolf/bmeck-ids#15]
> I have reviewed the document in anticipation of forwarding to IESG for publication.  There is still one outstanding issue and once that's resolved I will ask the AD to request publication.
> 
> https://mailarchive.ietf.org/arch/msg/dispatch/bHeezFbph08KIfXGvghHbqKWe14
> 
> I have just two minor comments with regards to the "Note to Readers" section in the front of the document, and the URI section.  Those sections reference a github repository for the document.  Since that repository isn't necessarily stable and not associated with the IETF, I would suggest to remove those sections OR add a "Note to the RFC editor" to remove those sections prior to publication.  
> 
> Regards,
> Mary

**Comment by mathiasbynens** [comment]
I've addressed the first point in #15.

For the second point, the URIs section is not part of the Markdown source file. Any idea how to remove it?

**Comment by linuxwolf** [comment]
It looks like #16 takes care of Mary's last point.
