### ISSUE TITLE
Remove goal parameter

### ISSUE THREAD

**Issue by mathiasbynens** [linuxwolf/bmeck-ids#9]
No browser vendor has expressed interest in pursuing the `goal` parameter, so we should remove it from this draft.

cc @annevk

**Comment by annevk** [comment]
My motivation for this is that there's been confusion about JavaScript MIME types for a long time. This draft finally puts that rest, by aligning the IETF/IANA view with that of the web platform. But then it adds this one thing that's not widely accepted at all and is really more of an idea. It would seem much more appropriate to incubate that separately.
